module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: [
    'react-native-reanimated/plugin',
    [
      'module-resolver',
      {
        root: ['./'],
        extensions: [
          '.ios.ts',
          '.android.ts',
          '.ts',
          '.ios.tsx',
          '.android.tsx',
          '.tsx',
          '.jsx',
          '.js',
          '.json',
        ],
        alias: {
          '~/api': './src/api',
          '~/assets/animations': './src/assets/animations',
          '~/assets/fonts': './src/assets/fonts',
          '~/assets/images': './src/assets/images',
          '~/assets/locales': './src/assets/locales',
          '~/assets/svg': './src/assets/svg',
          '~/components': './src/components',
          '~/scenes': './src/scenes',
          '~/services': './src/services',
          '~/modules': './src/modules',
          '~/stores': './src/stores',
          '~/tasks': './src/tasks',
          '~/theme': './src/theme',
          '~/steps': './src/steps',
          '~/steps/helpers': './src/steps/helpers',
          '~/navigation': './src/navigation',
          '~/navigation/routes': './src/navigation/routes.ts',
          '~/utils': './src/utils',
          '~/utils/config': './src/utils/config',
          '~/utils/types': './src/utils/types',
        },
      },
    ],
    ['@babel/plugin-proposal-decorators', { legacy: true }],
  ],
};
